BASEHOSTNAME = "wiki"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"  # Définition de Debian10 comme système d'exploitation de nos VM
  config.vm.box_check_update = false  # Empêchemant de la vérification de la version de la box

  # SSH
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"

  config.vm.define "#{BASEHOSTNAME}-server" do |server|
    server.vm.network "private_network", ip: "192.168.96.2"
    server.vm.network "forwarded_port", guest: 80, host: 8080
    server.vm.hostname = "#{BASEHOSTNAME}-server"  # Définition du nom de domaine de la VM

    config.vm.provision :shell, path: "crontab.sh", privileged: true
  end
  config.vm.define "#{BASEHOSTNAME}-backup" do |backup|
    backup.vm.network "private_network", ip: "192.168.96.10"
    backup.vm.network "forwarded_port", guest: 80, host: 8181
    backup.vm.hostname = "#{BASEHOSTNAME}-backup"  # Définition du nom de domaine de la VM
  end
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive # Désactivation de l'interactivité
    echo "####  MISE À JOUR DU SYSTÈME"
    sudo apt-get update
    echo "####  INSTALLATION DE APACHE ET PHP"
    sudo apt-get install php-geshi -y
    echo "####  TÉLÉCHARGEMENT DE DOKUWIKI"
    cd /tmp
    wget https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
    tar -xvf dokuwiki-stable.tgz
    echo "####  INSTALLATION DU DOKUWIKI"
    sudo rm /var/www/html/index.html
    sudo cp -r dokuwiki-2018-04-22b/* /var/www/html/
    sudo chown -R www-data /var/www/html/
    echo "####  INSTALLATION TERMINÉE"
  SHELL

  config.vm.provision :shell, path: "authorization.sh", privileged: true
end
