$script = <<-SCRIPT
echo "[!] Mise a jour des dépots"
apt update
echo "[!] Installation des dépendences"
apt-get -y install php php-curl php-apcu php-fpm php-bcmath php-gd php-intl php-pear php-imap php-memcache libapache2-mod-php php-pspell php-recode php-tidy php-xmlrpc php-mbstring php-gettext php-gmp php-json php-xml php-common
apt-get install wget apache2 rsync
usermod -a -G www-data vagrant
sudo mkdir /var/www/html/site1
chown -R vagrant:www-data /etc/apache2/sites-availabale/
chown -R vagrant:www-data /var/www/html/site1/
chown -R vagrant:www-data /var/www/html/
a2enmod proxy_fcgi setenvif
service apache2 start
echo "[!] Le serveur est pret"
SCRIPT

$master = <<-SCRIPT
cp /home/vagrant/id_rsa_wiki.pub /home/vagrant/.ssh/
cp /home/vagrant/id_rsa_wiki /home/vagrant/.ssh/
cat /home/vagrant/.ssh/id_rsa_wiki.pub >> /home/vagrant/.ssh/authorized_keys
chmod 600 /home/vagrant/.ssh/id_rsa_wiki.pub
chmod 600 /home/vagrant/.ssh/id_rsa_wiki
chmod 755 /home/vagrant/
echo "*/5 * * * * rsync --progress -avz -e 'ssh -o StrictHostKeyChecking=no -i /home/vagrant/id_rsa_wiki' /var/www/html/site1/ vagrant@192.168.56.10:/var/www/html/site1/" | sudo -u vagrant crontab
sudo service cron restart
SCRIPT


$apache = <<-SCRIPT
cat /home/vagrant/000-default.conf >> /etc/apache2/sites-available/000-default.conf
sed -i -e 's/#ServerName www.example.com/ServerName wiki.lab.local/' /etc/apache2/sites-available/000-default.conf
service apache2 restart
SCRIPT

$apacheback = <<-SCRIPT
cat /home/vagrant/000-default.conf >> /etc/apache2/sites-available/000-default.conf
sed -i -e 's/#ServerName www.example.com/ServerName wiki.lab.local.backup/' /etc/apache2/sites-available/000-default.conf
service apache2 restart
SCRIPT


$backup = <<-SCRIPT
cp /home/vagrant/id_rsa_wiki /home/vagrant/.ssh/
cp /home/vagrant/id_rsa_wiki.pub /home/vagrant/.ssh/
cat /home/vagrant/.ssh/id_rsa_wiki.pub >> /home/vagrant/.ssh/authorized_keys
chmod 600 /home/vagrant/.ssh/id_rsa_wiki
chmod 600 /home/vagrant/.ssh/id_rsa_wiki.pub
chmod 755 /home/vagrant/
SCRIPT

Vagrant.configure(2) do |config|
	config.vm.box = "debian/stretch64"
	config.vm.define "master" do |master|
		master.vm.box_check_update = false
		master.vm.network "private_network", ip: "192.168.56.3"
		master.vm.network "forwarded_port", guest: 80, host: 8080
		master.vm.hostname = "master"
		master.vm.provision "shell", inline: $script
		master.vm.provision "file", source: "file/index.html", destination: "/var/www/html/"
		master.vm.provision "file", source: "index.html", destination: "/var/www/html/site1/"
		master.vm.provision "file", source: "id_rsa_wiki.pub", destination: "/home/vagrant/"
		master.vm.provision "file", source: "id_rsa_wiki", destination: "/home/vagrant/"
		master.vm.provision "file", source: "something.html", destination: "/var/www/html/site1/"
		master.vm.provision "shell", inline: $master
		master.vm.provision "file", source: "virtualhost", destination: "/home/vagrant/000-default.conf"
		master.vm.provision "shell", inline: $apache
	end

	config.vm.define "backup" do |backup|
		backup.vm.box_check_update = false
		backup.vm.network "private_network", ip: "192.168.56.10"
		backup.vm.network "forwarded_port", guest: 80, host: 8181
		backup.vm.hostname = "backup"
		backup.vm.provision "shell", inline: $script
		backup.vm.provision "file", source: "file/index.html", destination: "/var/www/html/"
		backup.vm.provision "file", source: "index.html", destination: "/var/www/html/site1/"
		backup.vm.provision "file", source: "id_rsa_wiki", destination: "/home/vagrant/"
		backup.vm.provision "file", source: "id_rsa_wiki.pub", destination: "/home/vagrant/"
		backup.vm.provision "shell", inline: $backup
		backup.vm.provision "file", source: "virtualhost", destination: "/home/vagrant/000-default.conf"
		backup.vm.provision "shell", inline: $apacheback

	end
end
